#! /usr/bin/env node

'use strict';

let pkg = require('./package.json');
let R = require('ramda');
let Vorpal = require('vorpal');

let cli = new Vorpal();

let plugin = (name) => require(name)(cli);

let extend = R.pipe(
  R.map(plugin),
  R.bind(Promise.all, Promise)
);

let parse = () => cli.parse(process.argv);

process.on('SIGINT', () => process.exit(2));

plugin('./lib/extensions/rc')
  .then(() => extend(pkg.config.cli.plugins))
  .then(parse)
  .catch(err => console.error(err.stack));
